<template><div><p>由于业务对页面性能要求很高，如果下拉框数据很大，如果一个页面有多个下拉框，那么就导致页面很卡顿。由于elementPlus已经支持了下拉组件虚拟列表，但是所在项目仍然使用elementUI2.0，所以需要自己扩展支持下拉组件虚拟列表，以下是笔者总结的一篇关于elementUI2.0支持下拉框虚拟列表的实践方案，希望看完在项目中有所帮助。</p>
<p>正文开始...</p>
<p>在开始本文之前，笔者主要会从以下方向上去实现该业务需求</p>
<p>1、尝试在原有<code v-pre>elementUI</code>组件上，写一个自定义指令，支持下拉虚拟列表</p>
<p>2、尝试使用社区成熟的<code v-pre>虚拟列表</code>插件方案实现虚拟列表</p>
<h3 id="前置" tabindex="-1"><a class="header-anchor" href="#前置" aria-hidden="true">#</a> 前置</h3>
<p>我们知道<code v-pre>虚拟列表</code>本质上就是在可视区域内显示对应的数据，由于数据是按需加载，所以我们首先就要明白如何实现虚拟列表，具体可以参考以前写的一篇文章<a href="https://mp.weixin.qq.com/s?__biz=Mzk0ODMxODIzNw==&amp;mid=2247487858&amp;idx=1&amp;sn=7f7e5d6e3430438bcad17ca85c8d6c6f&amp;chksm=c3682800f41fa1167e57552bb701483b760deeaa1cb3b2597e59064c4c02c80b78bf893a1e14#rd" target="_blank" rel="noopener noreferrer">了解虚拟列表背后原理，轻松实现虚拟列表<ExternalLinkIcon/></a></p>
<h3 id="快速实现页面" tabindex="-1"><a class="header-anchor" href="#快速实现页面" aria-hidden="true">#</a> 快速实现页面</h3>
<p>我们是使用<code v-pre>vue-cli2</code>快速搭建了一个基本项目</p>
<p><img src="https://files.mdnice.com/user/24614/19bfa554-6d8e-4e1f-b972-ab9f8fa1e4b7.png" alt="">
我们可以非常清晰的看到右侧下拉测试<code v-pre>100</code>条数据直接渲染出来的</p>
<p>我们看下实际代码</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code> <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>el-form-item</span> <span class="token attr-name">label</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>非虚拟列表-活动名称2<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>el-select</span> <span class="token attr-name">v-model</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>form.value<span class="token punctuation">"</span></span> <span class="token attr-name">placeholder</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>请选择<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>el-option</span>
          <span class="token attr-name">v-for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>item in sourceData<span class="token punctuation">"</span></span>
          <span class="token attr-name">:key</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>item.value<span class="token punctuation">"</span></span>
          <span class="token attr-name">:label</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>item.label<span class="token punctuation">"</span></span>
          <span class="token attr-name">:value</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>item.value<span class="token punctuation">"</span></span>
        <span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>el-option</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>el-select</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>el-form-item</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>对应数据就是在<code v-pre>created</code>中直接生成了一组<code v-pre>100</code>条数据</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'hello-word'</span><span class="token punctuation">,</span>
  <span class="token function">data</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">sourceData</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token function">created</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> arr <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Array</span><span class="token punctuation">(</span><span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">fill</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    arr<span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">v<span class="token punctuation">,</span> index</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>sourceData<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
        <span class="token literal-property property">value</span><span class="token operator">:</span> index<span class="token punctuation">,</span>
        <span class="token literal-property property">label</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">test_</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>index<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们先看下左侧虚拟列表
<img src="https://files.mdnice.com/user/24614/e355e825-8995-4b6d-a880-cfdb8b67a8f7.png" alt=""></p>
<p>下拉框并不是一次性渲染所有数据，而是按需获取可视区域的数据，这是如何实现的？</p>
<h3 id="虚拟列表指令" tabindex="-1"><a class="header-anchor" href="#虚拟列表指令" aria-hidden="true">#</a> 虚拟列表指令</h3>
<p>主要思路就是控制下拉数据显示条数，本质就是要控制<code v-pre>optionsData</code></p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code> <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>el-form-item</span> <span class="token attr-name">label</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>虚拟列表-活动名称<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>el-select</span>
        <span class="token attr-name">v-model</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>form.value1<span class="token punctuation">"</span></span>
        <span class="token attr-name">placeholder</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>请选择<span class="token punctuation">"</span></span>
        <span class="token attr-name">@visible-change</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>handleVisibleChange<span class="token punctuation">"</span></span>
        <span class="token attr-name">v-select</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{ ...selectAttrs, data: sourceData }<span class="token punctuation">"</span></span>
      <span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>el-option</span>
          <span class="token attr-name">v-for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>item in optionsData<span class="token punctuation">"</span></span>
          <span class="token attr-name">:key</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>item.value<span class="token punctuation">"</span></span>
          <span class="token attr-name">:label</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>item.label<span class="token punctuation">"</span></span>
          <span class="token attr-name">:value</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>item.value<span class="token punctuation">"</span></span>
        <span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>el-option</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>el-select</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>el-form-item</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们看到<code v-pre>v-select</code>指令上主要有<code v-pre>data</code>,<code v-pre>selectAttrs</code>,<code v-pre>data</code>是原数据，<code v-pre>selectAttrs</code>主要是虚拟列表需要的参数</p>
<ul>
<li><code v-pre>selectAttrs</code></li>
</ul>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'hello-world'</span><span class="token punctuation">,</span>
  <span class="token function">data</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">sourceData</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token comment">// 原始数据</span>
      <span class="token literal-property property">selectAttrs</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">viewHeight</span><span class="token operator">:</span> <span class="token number">220</span><span class="token punctuation">,</span> <span class="token comment">// 可视区域的高度</span>
        <span class="token literal-property property">rowHeight</span><span class="token operator">:</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token comment">// 当前行的默认高度</span>
        <span class="token literal-property property">startIndex</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
        <span class="token literal-property property">endIndex</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
        <span class="token literal-property property">callback</span><span class="token operator">:</span> <span class="token keyword">this</span><span class="token punctuation">.</span>updateOptions<span class="token punctuation">,</span>
        <span class="token literal-property property">scrollView</span><span class="token operator">:</span> <span class="token keyword">null</span> <span class="token comment">// 滚动容器</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>从指令配置所需要的参数来看，主要是以下几个关键字段：</p>
<p><code v-pre>viewHeight</code>可视区域的高度</p>
<p><code v-pre>rowHeight</code>当前行的默认高度</p>
<p><code v-pre>startIndex</code>数据起始位置</p>
<p><code v-pre>endIndex</code>数据默认位置</p>
<p><code v-pre>callback</code>执行回调，主要是控制下拉数据</p>
<p><code v-pre>scrollView</code>监听滚动容器</p>
<p>然后我们看下指令是如何编写的</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> selectDirectives <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">wrap</span><span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">,</span>
  <span class="token literal-property property">fn</span><span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">,</span>
  <span class="token literal-property property">select</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token function">inserted</span> <span class="token punctuation">(</span><span class="token parameter">el<span class="token punctuation">,</span> binding<span class="token punctuation">,</span> vnode</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">let</span> <span class="token punctuation">{</span> data<span class="token punctuation">,</span> rowHeight<span class="token punctuation">,</span> startIndex<span class="token punctuation">,</span> callback<span class="token punctuation">,</span> filterable <span class="token punctuation">}</span> <span class="token operator">=</span> binding<span class="token punctuation">.</span>value<span class="token punctuation">;</span>
      <span class="token keyword">const</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">componentInstance</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">$children</span><span class="token operator">:</span> children <span class="token punctuation">}</span>
      <span class="token punctuation">}</span> <span class="token operator">=</span> vnode<span class="token punctuation">;</span>
      <span class="token keyword">const</span> selectDown <span class="token operator">=</span> children<span class="token punctuation">[</span>children<span class="token punctuation">.</span>length <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
      <span class="token keyword">const</span> <span class="token punctuation">[</span>elScrollBar<span class="token punctuation">]</span> <span class="token operator">=</span> selectDown<span class="token punctuation">.</span>$children<span class="token punctuation">;</span>
      <span class="token keyword">const</span> <span class="token punctuation">[</span>wrap<span class="token punctuation">]</span> <span class="token operator">=</span> elScrollBar<span class="token punctuation">.</span>$el<span class="token punctuation">.</span>childNodes<span class="token punctuation">;</span>
      <span class="token keyword">const</span> scrollView <span class="token operator">=</span> wrap<span class="token punctuation">.</span><span class="token function">getElementsByClassName</span><span class="token punctuation">(</span><span class="token string">'el-scrollbar__view'</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
      <span class="token keyword">const</span> total <span class="token operator">=</span> data<span class="token punctuation">.</span>length<span class="token punctuation">;</span> <span class="token comment">// 所有数据的总条数</span>
      <span class="token comment">// 设置el-scrollbar__view的高度</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span>filterable<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        scrollView<span class="token punctuation">.</span>style<span class="token punctuation">.</span>height <span class="token operator">=</span> <span class="token string">'auto'</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
        scrollView<span class="token punctuation">.</span>style<span class="token punctuation">.</span>height <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>total <span class="token operator">*</span> rowHeight<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">px</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
      <span class="token keyword">let</span> timer <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
      <span class="token keyword">const</span> <span class="token function-variable function">fn</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>timer<span class="token punctuation">)</span> <span class="token punctuation">{</span>
          <span class="token keyword">return</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        timer <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
        <span class="token keyword">const</span> requestId <span class="token operator">=</span> <span class="token function">setTimeout</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
          timer <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
          <span class="token keyword">const</span> scrollTop <span class="token operator">=</span> wrap<span class="token punctuation">.</span>scrollTop<span class="token punctuation">;</span>
          <span class="token comment">// 计算当前滚动位置，获取当前开始的起始位置</span>
          <span class="token keyword">const</span> currentIndex <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">floor</span><span class="token punctuation">(</span>scrollTop <span class="token operator">/</span> rowHeight<span class="token punctuation">)</span><span class="token punctuation">;</span>
          <span class="token comment">// console.log(startIndex, 'startIndex222', currentIndex);</span>
          <span class="token comment">// 根据滚动条获取当前索引与起始索引不相等时，将滚动的当前位置设置为起始位置</span>
          <span class="token keyword">if</span> <span class="token punctuation">(</span>currentIndex <span class="token operator">!==</span> startIndex<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            startIndex <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">max</span><span class="token punctuation">(</span>currentIndex<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
          <span class="token punctuation">}</span>
          <span class="token keyword">const</span> paddingTop <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>startIndex <span class="token operator">*</span> rowHeight<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">px</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">;</span>
          scrollView<span class="token punctuation">.</span>style<span class="token punctuation">.</span>paddingTop <span class="token operator">=</span> paddingTop<span class="token punctuation">;</span>
          <span class="token comment">// eslint-disable-next-line standard/no-callback-literal</span>
          <span class="token function">callback</span><span class="token punctuation">(</span><span class="token punctuation">{</span> startIndex<span class="token punctuation">,</span> scrollView <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>requestId<span class="token punctuation">)</span> <span class="token punctuation">{</span>
          <span class="token function">clearTimeout</span><span class="token punctuation">(</span>requestId<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
      <span class="token punctuation">}</span><span class="token punctuation">;</span>
      selectDirectives<span class="token punctuation">.</span>fn <span class="token operator">=</span> fn<span class="token punctuation">;</span>
      selectDirectives<span class="token punctuation">.</span>wrap <span class="token operator">=</span> wrap<span class="token punctuation">;</span>
      wrap<span class="token punctuation">.</span><span class="token function">addEventListener</span><span class="token punctuation">(</span><span class="token string">'scroll'</span><span class="token punctuation">,</span> fn<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token function">unbind</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      selectDirectives<span class="token punctuation">.</span>wrap<span class="token punctuation">.</span><span class="token function">removeEventListener</span><span class="token punctuation">(</span><span class="token string">'scroll'</span><span class="token punctuation">,</span> selectDirectives<span class="token punctuation">.</span>fn<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>关键的几点</p>
<p>1、找到内容滚动容器<code v-pre>wrap</code>，主要是通过<code v-pre>componentInstance</code>找到下拉滚动父容器</p>
<p>2、设置滚动容器内部高度<code v-pre>scrollView</code>【必须要设置】,不设置的话，内容数据将无法滚动显示</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">let</span> <span class="token punctuation">{</span> data<span class="token punctuation">,</span> rowHeight<span class="token punctuation">,</span> startIndex<span class="token punctuation">,</span> callback <span class="token punctuation">}</span> <span class="token operator">=</span> binding<span class="token punctuation">.</span>value<span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">componentInstance</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">$children</span><span class="token operator">:</span> children <span class="token punctuation">}</span>
<span class="token punctuation">}</span> <span class="token operator">=</span> vnode<span class="token punctuation">;</span>
<span class="token keyword">const</span> selectDown <span class="token operator">=</span> children<span class="token punctuation">[</span>children<span class="token punctuation">.</span>length <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token punctuation">[</span>elScrollBar<span class="token punctuation">]</span> <span class="token operator">=</span> selectDown<span class="token punctuation">.</span>$children<span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token punctuation">[</span>wrap<span class="token punctuation">]</span> <span class="token operator">=</span> elScrollBar<span class="token punctuation">.</span>$el<span class="token punctuation">.</span>childNodes<span class="token punctuation">;</span>
<span class="token keyword">const</span> scrollView <span class="token operator">=</span> wrap<span class="token punctuation">.</span><span class="token function">getElementsByClassName</span><span class="token punctuation">(</span><span class="token string">'el-scrollbar__view'</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> total <span class="token operator">=</span> data<span class="token punctuation">.</span>length<span class="token punctuation">;</span> <span class="token comment">// 所有数据的总条数</span>
<span class="token comment">// 设置el-scrollbar__view的高度</span>
scrollView<span class="token punctuation">.</span>style<span class="token punctuation">.</span>height <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>total <span class="token operator">*</span> rowHeight<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">px</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>用一张图还原一下，为什么需要设置<code v-pre>scrollView</code>的高度，以及当内部容器滚动时，我们需要给内部设置一个<code v-pre>paddingTop</code>,不然显示就会有空白块
<img src="https://files.mdnice.com/user/24614/ac6f6ee4-7921-4f5b-8938-7932265d59e1.png" alt=""></p>
<p>3、确定当前滚动的起始位</p>
<p>主要是当我们滚动容器时，根据滚动的位置确定起始位,核心代码如下</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>   <span class="token keyword">const</span> scrollTop <span class="token operator">=</span> wrap<span class="token punctuation">.</span>scrollTop<span class="token punctuation">;</span>
   <span class="token comment">// 计算当前滚动位置，获取当前开始的起始位置</span>
  <span class="token keyword">const</span> currentIndex <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">floor</span><span class="token punctuation">(</span>scrollTop <span class="token operator">/</span> rowHeight<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// console.log(startIndex, 'startIndex222', currentIndex);</span>
  <span class="token comment">// 根据滚动条获取当前索引与起始索引不相等时，将滚动的当前位置设置为起始位置</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>currentIndex <span class="token operator">!==</span> startIndex<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    startIndex <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">max</span><span class="token punctuation">(</span>currentIndex<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token keyword">const</span> paddingTop <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>startIndex <span class="token operator">*</span> rowHeight<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">px</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">;</span>
  scrollView<span class="token punctuation">.</span>style<span class="token punctuation">.</span>paddingTop <span class="token operator">=</span> paddingTop<span class="token punctuation">;</span>
  <span class="token comment">// eslint-disable-next-line standard/no-callback-literal</span>
  <span class="token function">callback</span><span class="token punctuation">(</span><span class="token punctuation">{</span> startIndex<span class="token punctuation">,</span> scrollView <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>4、我们看到有<code v-pre>callback</code>执行回调返回出去了<code v-pre>startIndex</code>,<code v-pre>scrollView</code></p>
<p>所以从最初设计指令时，我们看到了指令的<code v-pre>selectAttrs</code>上有一个<code v-pre>callback</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code> <span class="token operator">...</span>
 <span class="token literal-property property">selectAttrs</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">viewHeight</span><span class="token operator">:</span> <span class="token number">250</span><span class="token punctuation">,</span> <span class="token comment">// 可视区域的高度</span>
    <span class="token literal-property property">rowHeight</span><span class="token operator">:</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token comment">// 当前行的默认高度</span>
    <span class="token literal-property property">startIndex</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
    <span class="token literal-property property">endIndex</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
    <span class="token literal-property property">callback</span><span class="token operator">:</span> <span class="token keyword">this</span><span class="token punctuation">.</span>updateOptions<span class="token punctuation">,</span>
    <span class="token literal-property property">scrollView</span><span class="token operator">:</span> <span class="token keyword">null</span> <span class="token comment">// 滚动容器</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="指令执行回调" tabindex="-1"><a class="header-anchor" href="#指令执行回调" aria-hidden="true">#</a> 指令执行回调</h3>
<p>主要看<code v-pre>updateOptions</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token literal-property property">methods</span><span class="token operator">:</span> <span class="token punctuation">{</span>
  <span class="token function">updateOptions</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> startIndex<span class="token punctuation">,</span> scrollView <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>selectAttrs<span class="token punctuation">.</span>startIndex <span class="token operator">=</span> startIndex<span class="token punctuation">;</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>selectAttrs<span class="token punctuation">.</span>scrollView <span class="token operator">=</span> scrollView<span class="token punctuation">;</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">renderOptions</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
   <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们看下<code v-pre>renderOptions</code>这个方法，主要是更新下拉框数据</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token operator">...</span>
 <span class="token function">renderOptions</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">let</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">selectAttrs</span><span class="token operator">:</span> <span class="token punctuation">{</span> viewHeight<span class="token punctuation">,</span> rowHeight<span class="token punctuation">,</span> startIndex<span class="token punctuation">,</span> endIndex <span class="token punctuation">}</span><span class="token punctuation">,</span>
        sourceData
      <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">;</span>
      <span class="token keyword">const</span> total <span class="token operator">=</span> sourceData<span class="token punctuation">.</span>length<span class="token punctuation">;</span>
      <span class="token comment">// 可视区域的条数</span>
      <span class="token keyword">const</span> limit <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">ceil</span><span class="token punctuation">(</span>viewHeight <span class="token operator">/</span> rowHeight<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token comment">// 设置末位索引</span>
      endIndex <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">min</span><span class="token punctuation">(</span>startIndex <span class="token operator">+</span> limit<span class="token punctuation">,</span> total<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>selectAttrs<span class="token punctuation">.</span>endIndex <span class="token operator">=</span> endIndex<span class="token punctuation">;</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>optionsData <span class="token operator">=</span> sourceData<span class="token punctuation">.</span><span class="token function">slice</span><span class="token punctuation">(</span>startIndex<span class="token punctuation">,</span> endIndex<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>以上比较关键的一行代码就是根据回调函数中的<code v-pre>startIndex</code>以及<code v-pre>limit</code>确认最后的<code v-pre>endIndex</code>,
以下是核心关键代码</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code> <span class="token keyword">const</span> limit <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">ceil</span><span class="token punctuation">(</span>viewHeight <span class="token operator">/</span> rowHeight<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token comment">// 设置末位索引</span>
 endIndex <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">min</span><span class="token punctuation">(</span>startIndex <span class="token operator">+</span> limit<span class="token punctuation">,</span> total<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>最后我们就是根据起始位对愿数数据进行<code v-pre>slice</code>操作，确认真正需要显示的数据</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">this</span><span class="token punctuation">.</span>optionsData <span class="token operator">=</span> sourceData<span class="token punctuation">.</span><span class="token function">slice</span><span class="token punctuation">(</span>startIndex<span class="token punctuation">,</span> endIndex<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>对应的页面显示</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>el-select</span>
    <span class="token attr-name">v-model</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>form.value1<span class="token punctuation">"</span></span>
    <span class="token attr-name">placeholder</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>请选择<span class="token punctuation">"</span></span>
    <span class="token attr-name">@visible-change</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>handleVisibleChange<span class="token punctuation">"</span></span>
    <span class="token attr-name">v-select</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{ ...selectAttrs, data: sourceData }<span class="token punctuation">"</span></span>
 <span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>el-option</span>
      <span class="token attr-name">v-for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>item in optionsData<span class="token punctuation">"</span></span>
      <span class="token attr-name">:key</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>item.value<span class="token punctuation">"</span></span>
      <span class="token attr-name">:label</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>item.label<span class="token punctuation">"</span></span>
      <span class="token attr-name">:value</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>item.value<span class="token punctuation">"</span></span>
    <span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>el-option</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>el-select</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后我们注意到，我们在下拉框下绑定了一个<code v-pre>@visible-change=&quot;handleVisibleChange&quot;</code>方法，实际上只有我们在打开下拉框时才会需要触发更新下拉，所以我们需要调用<code v-pre>renderOptions</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token operator">...</span>
 <span class="token function">handleVisibleChange</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">selectAttrs</span><span class="token operator">:</span> <span class="token punctuation">{</span> scrollView <span class="token punctuation">}</span>
    <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">;</span>
    <span class="token comment">// 当打开下拉框时，重置scrollView的paadingTop,避免白屏</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>scrollView<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      scrollView<span class="token punctuation">.</span>style<span class="token punctuation">.</span>paddingTop <span class="token operator">=</span> <span class="token string">'0px'</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">renderOptions</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>但是我们注意到，这里我们重置了<code v-pre>scrollView</code>的<code v-pre>paddingTop</code>,因为我们在滚动时设置了<code v-pre>paddingTop</code>,所以此时我们需要重置<code v-pre>paddingTop</code>就是为了回显我们上次选择的内容区域</p>
<p>由于我们设置了内容器的高度，所以如果有设置过滤搜索，就会显示有问题，于是我们在过滤搜索时，就将高度置<code v-pre>auto</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">let</span> <span class="token punctuation">{</span> data<span class="token punctuation">,</span> rowHeight<span class="token punctuation">,</span> startIndex<span class="token punctuation">,</span> callback<span class="token punctuation">,</span> filterable <span class="token punctuation">}</span> <span class="token operator">=</span> binding<span class="token punctuation">.</span>value<span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">componentInstance</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">$children</span><span class="token operator">:</span> children <span class="token punctuation">}</span>
 <span class="token punctuation">}</span> <span class="token operator">=</span> vnode<span class="token punctuation">;</span>
  <span class="token keyword">const</span> selectDown <span class="token operator">=</span> children<span class="token punctuation">[</span>children<span class="token punctuation">.</span>length <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token keyword">const</span> <span class="token punctuation">[</span>elScrollBar<span class="token punctuation">]</span> <span class="token operator">=</span> selectDown<span class="token punctuation">.</span>$children<span class="token punctuation">;</span>
  <span class="token keyword">const</span> <span class="token punctuation">[</span>wrap<span class="token punctuation">]</span> <span class="token operator">=</span> elScrollBar<span class="token punctuation">.</span>$el<span class="token punctuation">.</span>childNodes<span class="token punctuation">;</span>
  <span class="token keyword">const</span> scrollView <span class="token operator">=</span> wrap<span class="token punctuation">.</span><span class="token function">getElementsByClassName</span><span class="token punctuation">(</span><span class="token string">'el-scrollbar__view'</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token keyword">const</span> total <span class="token operator">=</span> data<span class="token punctuation">.</span>length<span class="token punctuation">;</span> <span class="token comment">// 所有数据的总条数</span>
  <span class="token comment">// 设置el-scrollbar__view的高度</span>
<span class="token keyword">if</span> <span class="token punctuation">(</span>filterable<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    scrollView<span class="token punctuation">.</span>style<span class="token punctuation">.</span>height <span class="token operator">=</span> <span class="token string">'auto'</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
    scrollView<span class="token punctuation">.</span>style<span class="token punctuation">.</span>height <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>total <span class="token operator">*</span> rowHeight<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">px</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token operator">...</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="挂载指令" tabindex="-1"><a class="header-anchor" href="#挂载指令" aria-hidden="true">#</a> 挂载指令</h3>
<p>主要是局部注册就行</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// 指令</span>
<span class="token keyword">const</span> selectDirectives <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">wrap</span><span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">,</span>
  <span class="token literal-property property">fn</span><span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">,</span>
  <span class="token literal-property property">select</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token function">inserted</span> <span class="token punctuation">(</span><span class="token parameter">el<span class="token punctuation">,</span> binding<span class="token punctuation">,</span> vnode</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token operator">...</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后我们需要挂在在当前单文件中</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'HelloWorld'</span><span class="token punctuation">,</span>
  <span class="token function">data</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">msg</span><span class="token operator">:</span> <span class="token string">'Welcome to Your Vue.js App'</span><span class="token punctuation">,</span>
      <span class="token literal-property property">form</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">value1</span><span class="token operator">:</span> <span class="token string">''</span><span class="token punctuation">,</span>
        <span class="token literal-property property">value2</span><span class="token operator">:</span> <span class="token string">''</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
      <span class="token literal-property property">sourceData</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
      <span class="token literal-property property">optionsData</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
      <span class="token literal-property property">selectAttrs</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">viewHeight</span><span class="token operator">:</span> <span class="token number">220</span><span class="token punctuation">,</span> <span class="token comment">// 可视区域的高度</span>
        <span class="token literal-property property">rowHeight</span><span class="token operator">:</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token comment">// 当前行的默认高度</span>
        <span class="token literal-property property">startIndex</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
        <span class="token literal-property property">endIndex</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
        <span class="token literal-property property">callback</span><span class="token operator">:</span> <span class="token keyword">this</span><span class="token punctuation">.</span>updateOptions<span class="token punctuation">,</span>
        <span class="token literal-property property">scrollView</span><span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token comment">// 滚动容器</span>
        <span class="token literal-property property">filterable</span><span class="token operator">:</span> <span class="token boolean">true</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token literal-property property">directives</span><span class="token operator">:</span> selectDirectives<span class="token punctuation">,</span>
  <span class="token operator">...</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>最终结果就是下面这样了
<img src="https://files.mdnice.com/user/24614/2798088b-7162-49db-af8a-264077bcc651.png" alt=""></p>
<h3 id="vue-virtual-scroll-list插件实现虚拟列表" tabindex="-1"><a class="header-anchor" href="#vue-virtual-scroll-list插件实现虚拟列表" aria-hidden="true">#</a> vue-virtual-scroll-list插件实现虚拟列表</h3>
<p>在以上例子中我们尝试用自己写的指令已经满足虚拟列表，那如果不用自己写的指令，使用社区的方案，会不会更快，更简单呢？我们考虑主要是用这个<a href="https://github.com/tangbc/vue-virtual-scroll-list" title="社区插件" target="_blank" rel="noopener noreferrer">社区插件<ExternalLinkIcon/></a>，实现起来就更简单</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>hello<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>el-form</span> <span class="token attr-name">ref</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>form<span class="token punctuation">"</span></span> <span class="token attr-name">:model</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>form<span class="token punctuation">"</span></span> <span class="token attr-name">inline</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>el-form-item</span> <span class="token attr-name">label</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>活动名称<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>el-select</span>
          <span class="token attr-name">v-model</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>form.value<span class="token punctuation">"</span></span>
          <span class="token attr-name">placeholder</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>请选择<span class="token punctuation">"</span></span>
          <span class="token attr-name">@visible-change</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>handleVisibleChange<span class="token punctuation">"</span></span>
          <span class="token attr-name">ref</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>select<span class="token punctuation">"</span></span>
        <span class="token punctuation">></span></span>
          <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>virtual-list</span>
            <span class="token attr-name">:data-key</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span><span class="token punctuation">'</span>id<span class="token punctuation">'</span><span class="token punctuation">"</span></span>
            <span class="token attr-name">:data-sources</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sourceData<span class="token punctuation">"</span></span>
            <span class="token attr-name">:data-component</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>optionComponent<span class="token punctuation">"</span></span>
            <span class="token attr-name">:keeps</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>10<span class="token punctuation">"</span></span>
            <span class="token attr-name">:extra-props</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>extraProps<span class="token punctuation">"</span></span>
            <span class="token special-attr"><span class="token attr-name">style</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span><span class="token value css language-css"><span class="token property">max-height</span><span class="token punctuation">:</span> 245px<span class="token punctuation">;</span> <span class="token property">overflow-y</span><span class="token punctuation">:</span> auto<span class="token punctuation">;</span></span><span class="token punctuation">"</span></span></span>
          <span class="token punctuation">></span></span>
          <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>virtual-list</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>el-select</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>el-form-item</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>el-form</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>引入<code v-pre>vue-virtual-scroll-list</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> virtualList <span class="token keyword">from</span> <span class="token string">'vue-virtual-scroll-list'</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> optionComponent <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">props</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">source</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">type</span><span class="token operator">:</span> Object<span class="token punctuation">,</span>
      <span class="token keyword">default</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token literal-property property">label</span><span class="token operator">:</span> String<span class="token punctuation">,</span>
    <span class="token literal-property property">value</span><span class="token operator">:</span> String
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token literal-property property">template</span><span class="token operator">:</span>
    <span class="token string">'&lt;el-option :label="source[label]" :value="source[value]">&lt;/el-option>'</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'HelloWorld'</span><span class="token punctuation">,</span>
  <span class="token literal-property property">components</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    virtualList
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token function">data</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">msg</span><span class="token operator">:</span> <span class="token string">'Welcome to Your Vue.js App'</span><span class="token punctuation">,</span>
      <span class="token literal-property property">form</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">value</span><span class="token operator">:</span> <span class="token string">''</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
      optionComponent<span class="token punctuation">,</span>
      <span class="token literal-property property">sourceData</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
      <span class="token literal-property property">extraProps</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">label</span><span class="token operator">:</span> <span class="token string">'label'</span><span class="token punctuation">,</span>
        <span class="token literal-property property">value</span><span class="token operator">:</span> <span class="token string">'value'</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token literal-property property">methods</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token function">handleVisibleChange</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">const</span> select <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">.</span>$refs<span class="token punctuation">.</span>select<span class="token punctuation">;</span>
      <span class="token keyword">const</span> child <span class="token operator">=</span> select<span class="token punctuation">.</span>$children<span class="token punctuation">;</span>
      <span class="token keyword">const</span> <span class="token punctuation">[</span><span class="token punctuation">,</span> selectDrop<span class="token punctuation">]</span> <span class="token operator">=</span> child<span class="token punctuation">;</span>
      <span class="token keyword">const</span> <span class="token punctuation">[</span>cchild<span class="token punctuation">]</span> <span class="token operator">=</span> selectDrop<span class="token punctuation">.</span>$children<span class="token punctuation">;</span>
      <span class="token keyword">const</span> <span class="token punctuation">[</span>a<span class="token punctuation">]</span> <span class="token operator">=</span> cchild<span class="token punctuation">.</span>$children<span class="token punctuation">;</span>
      <span class="token keyword">const</span> <span class="token punctuation">[</span>group<span class="token punctuation">]</span> <span class="token operator">=</span> a<span class="token punctuation">.</span>$el<span class="token punctuation">.</span>children<span class="token punctuation">;</span>
      group<span class="token punctuation">.</span>style<span class="token punctuation">.</span>paddingTop <span class="token operator">=</span> <span class="token string">'0px'</span><span class="token punctuation">;</span>
      console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>group<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token function">created</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> arr <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Array</span><span class="token punctuation">(</span><span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">fill</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    arr<span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">v<span class="token punctuation">,</span> index</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>sourceData<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
        <span class="token literal-property property">value</span><span class="token operator">:</span> index<span class="token punctuation">,</span>
        <span class="token literal-property property">label</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">test_</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>index<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
        <span class="token literal-property property">id</span><span class="token operator">:</span> Math<span class="token punctuation">.</span><span class="token function">random</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们注意到<code v-pre>handleVisibleChange</code>同样是将滚动容器的<code v-pre>paddingTop</code>置零了，这样保证，打开下拉框时不会白屏。</p>
<p>并且如果是用插件，就必须要有<code v-pre>id</code>,<code v-pre>virtual-list</code>上指定<code v-pre>data-key</code></p>
<p><img src="https://files.mdnice.com/user/24614/27342bf0-f8fc-4bbd-a3d4-def5140ccd48.png" alt=""></p>
<h3 id="总结" tabindex="-1"><a class="header-anchor" href="#总结" aria-hidden="true">#</a> 总结</h3>
<ul>
<li>
<p>主要是写了一个指令，在<code v-pre>elementUI</code>的<code v-pre>select</code>组件上支持虚拟列表展示，我们在项目使用自定义指令支持下拉框的虚拟列表</p>
</li>
<li>
<p>使用第三方插件<code v-pre>vue-virtual-scroll-list</code>实现虚拟列表</p>
</li>
<li>
<p>本文实例源码<a href="https://github.com/maicFir/lessonNote/tree/master/vue/04-select%E4%B8%8B%E6%8B%89%E6%A1%86%E8%99%9A%E6%8B%9F%E5%88%97%E8%A1%A8&amp;%E6%8B%96%E6%8B%BD/elem-select" title="code example" target="_blank" rel="noopener noreferrer">code example<ExternalLinkIcon/></a></p>
</li>
<li>
<p>个人比较推荐社区优秀成熟的第三方库去满足我们的业务，自己虽然手写了一个指令支持虚拟列表，但是在业务时间紧凑的情况下，肯定优先使用插件，除非插件不满足我们自己的业务需求，那么只能自己造轮子了。</p>
</li>
</ul>
</div></template>
