<template><div><p><code v-pre>react</code>在企业项目中已经变成了一个必不可少的<code v-pre>UI</code>框架，从过去早期有<code v-pre>jquery</code>，后面有<code v-pre>bootstrap</code>兴起，<code v-pre>jquery</code>可以说二次封装的原生<code v-pre>js</code>，<code v-pre>bootstarp</code>可以快速搭建一个精美网页，现在基本很少用<code v-pre>bootstrap</code>和<code v-pre>jquery</code>了，基本上<code v-pre>vuejs</code>,<code v-pre>react</code>，<code v-pre>angular</code>三分天下，国内<code v-pre>vuejs</code>和<code v-pre>react</code>居多，<code v-pre>angular</code>很少用，本文是一篇笔者关于<code v-pre>react</code>相关的笔记，希望看完在项目中有所思考和帮助。</p>
<p>在开始本文之前，主要会从以下几个方面去认识学习<code v-pre>react</code></p>
<p>1、没有概念，用实际例子感受<code v-pre>react</code>核心思想</p>
<p>2、<code v-pre>react</code>数据流是怎么样，父子通信，<code v-pre>react</code>是如何更新数据</p>
<p>3、<code v-pre>class</code>组件与<code v-pre>纯函数</code>组件</p>
<p>4、<code v-pre>react</code>的状态提升</p>
<p>5、<code v-pre>react</code>组合概念</p>
<p>6、<code v-pre>react</code>设计哲学</p>
<p>正文开始...</p>
<h3 id="class组件" tabindex="-1"><a class="header-anchor" href="#class组件" aria-hidden="true">#</a> class组件</h3>
<p><code v-pre>react</code>的理念就是构建UI的一个库，很大一个特征就是<code v-pre>申明式</code>，<code v-pre>组件化</code>,<code v-pre>跨平台</code></p>
<ul>
<li>申明式</li>
</ul>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> React <span class="token keyword">from</span> <span class="token string">"react"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> ReactDOM <span class="token keyword">from</span> <span class="token string">'react-dom/client'</span><span class="token punctuation">;</span>
<span class="token keyword">class</span> <span class="token class-name">HelloMessage</span> <span class="token keyword">extends</span> <span class="token class-name">React<span class="token punctuation">.</span>Component</span> <span class="token punctuation">{</span>
  <span class="token function">constructor</span><span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">super</span><span class="token punctuation">(</span>props<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>state <span class="token operator">=</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">count</span><span class="token operator">:</span> <span class="token number">0</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
  <span class="token function">render</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token punctuation">(</span>
      <span class="token operator">&lt;</span>div<span class="token operator">></span>
        Hello <span class="token punctuation">{</span><span class="token keyword">this</span><span class="token punctuation">.</span>props<span class="token punctuation">.</span>name<span class="token punctuation">}</span>
      <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span>
    <span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token keyword">const</span> root <span class="token operator">=</span> ReactDOM<span class="token punctuation">.</span><span class="token function">createRoot</span><span class="token punctuation">(</span>document<span class="token punctuation">.</span><span class="token function">getElementById</span><span class="token punctuation">(</span><span class="token string">'hello-example'</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
root<span class="token punctuation">.</span><span class="token function">render</span><span class="token punctuation">(</span><span class="token operator">&lt;</span>HelloMessage name<span class="token operator">=</span><span class="token string">"Web技术学苑"</span> <span class="token operator">/</span><span class="token operator">></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>从以上我们知道就是用<code v-pre>class</code>申明了一个<code v-pre>HelloMessage</code>的组件，继承了<code v-pre>React.Component</code>组件，然后通过<code v-pre>root.render(&lt;HelloMessage /&gt;)</code>挂载到<code v-pre>dom</code>上，我们也会发现<code v-pre>HelloMessage</code>这个<code v-pre>class</code>组件中的<code v-pre>render</code>中返回的就是一个<code v-pre>jsx</code>,这就是挂载在<code v-pre>dom</code>上的具体内容</p>
<h3 id="纯函数组件" tabindex="-1"><a class="header-anchor" href="#纯函数组件" aria-hidden="true">#</a> 纯函数组件</h3>
<p>以上是<code v-pre>class</code>方式写的一个组件，但是从<code v-pre>react16.8</code> 版本后就出现了<code v-pre>hook</code>，也就是过去纯函数组件没有自己的状态，但是有了<code v-pre>hook</code>后，纯函数组件就可以有自己的状态了。我们完全可以用<code v-pre>函数组件</code>和<code v-pre>hook</code>替代<code v-pre>class</code>组件，上面一段代码，如果用<code v-pre>函数组件</code>就是下面这样的</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> React<span class="token punctuation">,</span> <span class="token punctuation">{</span> useState <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"react"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> ReactDOM <span class="token keyword">from</span> <span class="token string">'react-dom/client'</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">HelloMessage</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
 <span class="token keyword">const</span> <span class="token punctuation">[</span>count<span class="token punctuation">,</span> setCount<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">useState</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">return</span> <span class="token punctuation">(</span>
      <span class="token operator">&lt;</span>div<span class="token operator">></span>
        Hello <span class="token punctuation">{</span>props<span class="token punctuation">.</span>name<span class="token punctuation">}</span>
      <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span>
    <span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token keyword">const</span> root <span class="token operator">=</span> ReactDOM<span class="token punctuation">.</span><span class="token function">createRoot</span><span class="token punctuation">(</span>document<span class="token punctuation">.</span><span class="token function">getElementById</span><span class="token punctuation">(</span><span class="token string">'hello-example'</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
root<span class="token punctuation">.</span><span class="token function">render</span><span class="token punctuation">(</span><span class="token operator">&lt;</span>HelloMessage name<span class="token operator">=</span><span class="token string">"Web技术学苑"</span> <span class="token operator">/</span><span class="token operator">></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="状态提升" tabindex="-1"><a class="header-anchor" href="#状态提升" aria-hidden="true">#</a> 状态提升</h3>
<p>我们知道每个组件有自己的<code v-pre>state</code>，如果同一个组件内部都是自己的<code v-pre>state</code>，那么组件之间就是互相独立，但是此时我想让一个组件输入值，也会影响另一个组件，那么此时就需要两个组件的数据依赖来源就必须提升到父组件里去，所以这就是状态提升。</p>
<p>我们以人民币换算美元汇率的例子加深对<code v-pre>状态提升</code>概念的理解</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> React <span class="token keyword">from</span> <span class="token string">"react"</span><span class="token punctuation">;</span>
<span class="token keyword">class</span> <span class="token class-name">List</span> <span class="token keyword">extends</span> <span class="token class-name">React<span class="token punctuation">.</span>Component</span> <span class="token punctuation">{</span>
    <span class="token function">constructor</span><span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">super</span><span class="token punctuation">(</span>props<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span>state <span class="token operator">=</span> <span class="token punctuation">{</span>
            <span class="token literal-property property">count</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
            <span class="token literal-property property">price</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
            <span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token comment">// 0 人民币 1 代表美元</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
    <span class="token function-variable function">handleAdd</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        <span class="token comment">// this.setState({</span>
        <span class="token comment">//     count: ++this.state.count</span>
        <span class="token comment">// })</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">setState</span><span class="token punctuation">(</span><span class="token parameter">state</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token punctuation">{</span>
                <span class="token operator">...</span>state<span class="token punctuation">,</span>
                <span class="token literal-property property">count</span><span class="token operator">:</span> state<span class="token punctuation">.</span>count <span class="token operator">+</span> <span class="token number">1</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
    <span class="token function-variable function">handleReduce</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">setState</span><span class="token punctuation">(</span><span class="token parameter">state</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token punctuation">{</span>
                <span class="token literal-property property">count</span><span class="token operator">:</span> state<span class="token punctuation">.</span>count <span class="token operator">-</span> <span class="token number">1</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
    <span class="token function-variable function">handleRmbInput</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">e</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        <span class="token keyword">const</span> val <span class="token operator">=</span> e<span class="token punctuation">.</span>target<span class="token punctuation">.</span>value<span class="token punctuation">;</span>
        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>e<span class="token punctuation">)</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">setState</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
            <span class="token literal-property property">price</span><span class="token operator">:</span> val<span class="token punctuation">,</span>
            <span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token number">0</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
    <span class="token function-variable function">handleDollInput</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">e</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        <span class="token keyword">const</span> val <span class="token operator">=</span> e<span class="token punctuation">.</span>target<span class="token punctuation">.</span>value<span class="token punctuation">;</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">setState</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
            <span class="token literal-property property">price</span><span class="token operator">:</span> val<span class="token punctuation">,</span>
            <span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token number">1</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token function">render</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">const</span> <span class="token punctuation">{</span> count<span class="token punctuation">,</span> price<span class="token punctuation">,</span> type <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">.</span>state<span class="token punctuation">;</span>
        <span class="token keyword">const</span> <span class="token function-variable function">RmbInput</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> price<span class="token punctuation">,</span> handleChange <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token operator">&lt;</span>fieldset<span class="token operator">></span>
                <span class="token operator">&lt;</span>legend<span class="token operator">></span>人民币<span class="token operator">&lt;</span><span class="token operator">/</span>legend<span class="token operator">></span>
                <span class="token operator">&lt;</span>input value<span class="token operator">=</span><span class="token punctuation">{</span>price<span class="token punctuation">}</span>
                    onChange<span class="token operator">=</span><span class="token punctuation">{</span>handleChange<span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
            <span class="token operator">&lt;</span><span class="token operator">/</span>fieldset<span class="token operator">></span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span><span class="token punctuation">;</span>
        <span class="token keyword">const</span> <span class="token function-variable function">DollarInput</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> price<span class="token punctuation">,</span> handleChange <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token operator">&lt;</span>fieldset<span class="token operator">></span>
                <span class="token operator">&lt;</span>legend<span class="token operator">></span>美元<span class="token operator">&lt;</span><span class="token operator">/</span>legend<span class="token operator">></span>
                <span class="token operator">&lt;</span>input value<span class="token operator">=</span><span class="token punctuation">{</span>price<span class="token punctuation">}</span>
                    onChange<span class="token operator">=</span><span class="token punctuation">{</span>handleChange<span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
            <span class="token operator">&lt;</span><span class="token operator">/</span>fieldset<span class="token operator">></span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span><span class="token punctuation">;</span>
        <span class="token keyword">const</span> rmbVal <span class="token operator">=</span> type <span class="token operator">===</span> <span class="token number">0</span> <span class="token operator">?</span> price <span class="token operator">:</span> price <span class="token operator">*</span> <span class="token number">7.34</span><span class="token punctuation">;</span>
        <span class="token keyword">const</span> dollVal <span class="token operator">=</span> type <span class="token operator">===</span> <span class="token number">1</span> <span class="token operator">?</span> price <span class="token operator">:</span> <span class="token number">0.14</span> <span class="token operator">*</span> price<span class="token punctuation">;</span>
        <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token operator">&lt;</span>div className<span class="token operator">=</span><span class="token string">"list-app"</span> style<span class="token operator">=</span><span class="token punctuation">{</span><span class="token punctuation">{</span> <span class="token literal-property property">padding</span><span class="token operator">:</span> <span class="token string">'10px'</span> <span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">></span>
            <span class="token operator">&lt;</span>hr <span class="token operator">/</span><span class="token operator">></span>
            <span class="token operator">&lt;</span>button onClick<span class="token operator">=</span><span class="token punctuation">{</span><span class="token keyword">this</span><span class="token punctuation">.</span>handleAdd<span class="token punctuation">}</span><span class="token operator">></span><span class="token operator">+</span><span class="token operator">&lt;</span><span class="token operator">/</span>button<span class="token operator">></span>
            <span class="token operator">&lt;</span>span<span class="token operator">></span><span class="token punctuation">{</span>count<span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>span<span class="token operator">></span>
            <span class="token operator">&lt;</span>button onClick<span class="token operator">=</span><span class="token punctuation">{</span><span class="token keyword">this</span><span class="token punctuation">.</span>handleReduce<span class="token punctuation">}</span><span class="token operator">></span><span class="token operator">-</span><span class="token operator">&lt;</span><span class="token operator">/</span>button<span class="token operator">></span>
            <span class="token operator">&lt;</span>hr <span class="token operator">/</span><span class="token operator">></span>
            <span class="token operator">&lt;</span>RmbInput handleChange<span class="token operator">=</span><span class="token punctuation">{</span><span class="token keyword">this</span><span class="token punctuation">.</span>handleRmbInput<span class="token punctuation">}</span> price<span class="token operator">=</span><span class="token punctuation">{</span>rmbVal<span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
            <span class="token operator">&lt;</span>hr<span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">/</span>hr<span class="token operator">></span>
            <span class="token operator">&lt;</span>DollarInput handleChange<span class="token operator">=</span><span class="token punctuation">{</span><span class="token keyword">this</span><span class="token punctuation">.</span>handleDollInput<span class="token punctuation">}</span> price<span class="token operator">=</span><span class="token punctuation">{</span>dollVal<span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
        <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token keyword">export</span> <span class="token keyword">default</span> List
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们看到<code v-pre>List</code>这个组件返回的有<code v-pre>RmbInput</code>与<code v-pre>DollarInput</code>组件，你会发现实际上这两个组件的共同特征就是都传入了两个<code v-pre>props</code>到子组件中，注意其中一个是传入的是方法<code v-pre>handleChange</code>,通常在<code v-pre>react</code>中数据流是单向的，所以修改传入的子组件的<code v-pre>props</code>，通常是通过父组件的传入子组件的回调方法去修改传入子组件的<code v-pre>props</code></p>
<p>比如说下面这样一段伪代码</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// Parant</span>
<span class="token keyword">function</span> <span class="token function">Parent</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> <span class="token punctuation">{</span> name<span class="token punctuation">,</span> setName<span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">useState</span><span class="token punctuation">(</span><span class="token string">"Web技术学苑"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token operator">&lt;</span>div<span class="token operator">></span>
    <span class="token operator">&lt;</span>h1<span class="token operator">></span><span class="token punctuation">{</span>name<span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>h1<span class="token operator">></span>
    <span class="token operator">&lt;</span>Child name<span class="token operator">=</span><span class="token punctuation">{</span>name<span class="token punctuation">}</span> onChangeName<span class="token operator">=</span><span class="token punctuation">{</span><span class="token parameter">val</span> <span class="token operator">=></span> <span class="token function">setName</span><span class="token punctuation">(</span>val<span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token operator">/</span><span class="token operator">></span>
  <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>

<span class="token comment">// Child</span>
<span class="token keyword">function</span> <span class="token function">Child</span><span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token operator">&lt;</span>div<span class="token operator">></span>
    <span class="token operator">&lt;</span>input value<span class="token operator">=</span><span class="token punctuation">{</span>props<span class="token punctuation">.</span>name<span class="token punctuation">}</span> onChange<span class="token operator">=</span><span class="token punctuation">{</span><span class="token parameter">e</span> <span class="token operator">=></span> props<span class="token punctuation">.</span><span class="token function">onChangeName</span><span class="token punctuation">(</span>e<span class="token punctuation">.</span>target<span class="token punctuation">.</span>value<span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token operator">/</span><span class="token operator">></span>
  <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>最后我们看下最终的效果
<img src="https://files.mdnice.com/user/24614/aa02c70e-5664-49c1-a74c-84a943e86721.png" alt=""></p>
<p>因此一个计算汇率的功能就OK了</p>
<p>但是我们发现实际上<code v-pre>RmbInput</code>与<code v-pre>DollarInput</code>做的事情都是非常类似的，只有名称不一样，因此我们可以将这两个组件合并成一个组件，只需传入一个参数来判断名称即可。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> React <span class="token keyword">from</span> <span class="token string">"react"</span><span class="token punctuation">;</span>
<span class="token keyword">class</span> <span class="token class-name">List</span> <span class="token keyword">extends</span> <span class="token class-name">React<span class="token punctuation">.</span>Component</span> <span class="token punctuation">{</span>
    <span class="token function">constructor</span><span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">super</span><span class="token punctuation">(</span>props<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span>state <span class="token operator">=</span> <span class="token punctuation">{</span>
            <span class="token literal-property property">count</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
            <span class="token literal-property property">price</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
            <span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token comment">// 0 人民币 1 代表美元</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
   <span class="token operator">...</span>
   <span class="token function">render</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">const</span> <span class="token punctuation">{</span> count<span class="token punctuation">,</span> price<span class="token punctuation">,</span> type <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">.</span>state<span class="token punctuation">;</span>
        <span class="token comment">// 合并成一个组件了</span>
        <span class="token keyword">const</span> <span class="token function-variable function">ExchangeInput</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> price<span class="token punctuation">,</span> handleChange<span class="token punctuation">,</span> type <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token operator">&lt;</span>fieldset<span class="token operator">></span>
                <span class="token operator">&lt;</span>legend<span class="token operator">></span><span class="token punctuation">{</span>type <span class="token operator">===</span> <span class="token string">"RmbInput"</span> <span class="token operator">?</span> <span class="token string">'人民币'</span> <span class="token operator">:</span> <span class="token string">'美元'</span><span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>legend<span class="token operator">></span>
                <span class="token operator">&lt;</span>input value<span class="token operator">=</span><span class="token punctuation">{</span>price<span class="token punctuation">}</span>
                    onChange<span class="token operator">=</span><span class="token punctuation">{</span>handleChange<span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
            <span class="token operator">&lt;</span><span class="token operator">/</span>fieldset<span class="token operator">></span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">const</span> rmbVal <span class="token operator">=</span> type <span class="token operator">===</span> <span class="token number">0</span> <span class="token operator">?</span> price <span class="token operator">:</span> price <span class="token operator">*</span> <span class="token number">7.34</span><span class="token punctuation">;</span>
        <span class="token keyword">const</span> dollVal <span class="token operator">=</span> type <span class="token operator">===</span> <span class="token number">1</span> <span class="token operator">?</span> price <span class="token operator">:</span> <span class="token number">0.14</span> <span class="token operator">*</span> price<span class="token punctuation">;</span>
        <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token operator">&lt;</span>div className<span class="token operator">=</span><span class="token string">"list-app"</span> style<span class="token operator">=</span><span class="token punctuation">{</span><span class="token punctuation">{</span> <span class="token literal-property property">padding</span><span class="token operator">:</span> <span class="token string">'10px'</span> <span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">></span>
            <span class="token operator">&lt;</span>hr <span class="token operator">/</span><span class="token operator">></span>
            <span class="token operator">&lt;</span>button onClick<span class="token operator">=</span><span class="token punctuation">{</span><span class="token keyword">this</span><span class="token punctuation">.</span>handleAdd<span class="token punctuation">}</span><span class="token operator">></span><span class="token operator">+</span><span class="token operator">&lt;</span><span class="token operator">/</span>button<span class="token operator">></span>
            <span class="token operator">&lt;</span>span<span class="token operator">></span><span class="token punctuation">{</span>count<span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>span<span class="token operator">></span>
            <span class="token operator">&lt;</span>button onClick<span class="token operator">=</span><span class="token punctuation">{</span><span class="token keyword">this</span><span class="token punctuation">.</span>handleReduce<span class="token punctuation">}</span><span class="token operator">></span><span class="token operator">-</span><span class="token operator">&lt;</span><span class="token operator">/</span>button<span class="token operator">></span>
            <span class="token operator">&lt;</span>hr <span class="token operator">/</span><span class="token operator">></span>
            <span class="token operator">&lt;</span>ExchangeInput handleChange<span class="token operator">=</span><span class="token punctuation">{</span><span class="token keyword">this</span><span class="token punctuation">.</span>handleRmbInput<span class="token punctuation">}</span> price<span class="token operator">=</span><span class="token punctuation">{</span>rmbVal<span class="token punctuation">}</span> type<span class="token operator">=</span><span class="token string">"RmbInput"</span><span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">/</span>ExchangeInput<span class="token operator">></span>
            <span class="token operator">&lt;</span>hr<span class="token operator">/</span><span class="token operator">></span>
            <span class="token operator">&lt;</span>ExchangeInput handleChange<span class="token operator">=</span><span class="token punctuation">{</span><span class="token keyword">this</span><span class="token punctuation">.</span>handleDollInput<span class="token punctuation">}</span> price<span class="token operator">=</span><span class="token punctuation">{</span>dollVal<span class="token punctuation">}</span> type<span class="token operator">=</span><span class="token string">"DollarInput"</span><span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">/</span>ExchangeInput<span class="token operator">></span>
        <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token keyword">export</span> <span class="token keyword">default</span> List
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>因此从<code v-pre>状态提升</code>来看，<code v-pre>react</code>组件的<code v-pre>state</code>本该相互独立，但是如果想实现一个组件修改关联另一个组件修改，那么数据来源必须依赖父组件，所以也就只能把当前组件的<code v-pre>state</code>提升到父组件里去，从而实现了状态提升。</p>
<p>这里我们也发现，<code v-pre>react</code>提供给子组件的通信就是<code v-pre>props</code>,修改当前组件的<code v-pre>state</code>就是依赖<code v-pre>setState</code>,要想修改父组件数据就是通过<code v-pre>props</code>传入子组件的回调去修改的。</p>
<h3 id="react组合" tabindex="-1"><a class="header-anchor" href="#react组合" aria-hidden="true">#</a> react组合</h3>
<p>在react<code v-pre>组合</code>类似<code v-pre>vue</code>的插槽一样的概念，不过有些区别</p>
<p><code v-pre>props.children</code>就是默认渲染所有父组件的<code v-pre>插槽</code>内容</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> React <span class="token keyword">from</span> <span class="token string">"react"</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">Title</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token operator">&lt;</span>div className<span class="token operator">=</span><span class="token string">"title"</span> style<span class="token operator">=</span><span class="token punctuation">{</span><span class="token punctuation">{</span> <span class="token literal-property property">display</span><span class="token operator">:</span> <span class="token string">'flex'</span> <span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">></span>
        <span class="token punctuation">{</span>props<span class="token punctuation">.</span>children<span class="token punctuation">}</span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
<span class="token keyword">const</span> <span class="token function-variable function">About</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token operator">&lt;</span>div<span class="token operator">></span>
    <span class="token operator">&lt;</span>Title<span class="token operator">></span>
        <span class="token operator">&lt;</span>h1<span class="token operator">></span>Web技术学苑<span class="token operator">&lt;</span><span class="token operator">/</span>h1<span class="token operator">></span>
        <span class="token operator">&lt;</span>div<span class="token operator">></span>Maic<span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>Title<span class="token operator">></span>
<span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span>

<span class="token keyword">export</span> <span class="token keyword">default</span> About<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这样你看到的结果就是下面这样的
<img src="https://files.mdnice.com/user/24614/4bef4445-92f0-4e7b-b8f3-e1bfa280d74e.png" alt=""></p>
<p>你也可以通过<code v-pre>props</code>做类似的<code v-pre>vue</code>具名插槽的功能</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> React <span class="token keyword">from</span> <span class="token string">"react"</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">Title</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token operator">&lt;</span>div className<span class="token operator">=</span><span class="token string">"title"</span> style<span class="token operator">=</span><span class="token punctuation">{</span><span class="token punctuation">{</span> <span class="token literal-property property">display</span><span class="token operator">:</span> <span class="token string">'flex'</span> <span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">></span>
        <span class="token punctuation">{</span>props<span class="token punctuation">.</span>children<span class="token punctuation">}</span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
<span class="token keyword">const</span> <span class="token function-variable function">Content</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token operator">&lt;</span>div className<span class="token operator">=</span><span class="token string">"content"</span> style<span class="token operator">=</span><span class="token punctuation">{</span><span class="token punctuation">{</span> <span class="token operator">...</span>props<span class="token punctuation">.</span>style <span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">></span>
        <span class="token punctuation">{</span>props<span class="token punctuation">.</span>left<span class="token punctuation">}</span>
        <span class="token punctuation">{</span>props<span class="token punctuation">.</span>children<span class="token punctuation">}</span>
        <span class="token punctuation">{</span>props<span class="token punctuation">.</span>right<span class="token punctuation">}</span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
<span class="token keyword">const</span> <span class="token function-variable function">About</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> <span class="token function-variable function">Left</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">(</span><span class="token operator">&lt;</span>div<span class="token operator">></span>left<span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> <span class="token function-variable function">Right</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">(</span><span class="token operator">&lt;</span>div<span class="token operator">></span>right<span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token operator">&lt;</span>div<span class="token operator">></span>
        <span class="token operator">&lt;</span>Title<span class="token operator">></span>
            <span class="token operator">&lt;</span>h1<span class="token operator">></span>Web技术学苑<span class="token operator">&lt;</span><span class="token operator">/</span>h1<span class="token operator">></span>
            <span class="token operator">&lt;</span>div<span class="token operator">></span>Maic<span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span>
        <span class="token operator">&lt;</span><span class="token operator">/</span>Title<span class="token operator">></span>
        <span class="token operator">&lt;</span>Content 
          style<span class="token operator">=</span><span class="token punctuation">{</span><span class="token punctuation">{</span> <span class="token literal-property property">padding</span><span class="token operator">:</span> <span class="token string">'10px'</span> <span class="token punctuation">}</span><span class="token punctuation">}</span> 
          left<span class="token operator">=</span><span class="token punctuation">{</span><span class="token operator">&lt;</span>Left <span class="token operator">/</span><span class="token operator">></span><span class="token punctuation">}</span> 
          right<span class="token operator">=</span><span class="token punctuation">{</span><span class="token operator">&lt;</span>Right <span class="token operator">/</span><span class="token operator">></span><span class="token punctuation">}</span>
        <span class="token operator">></span>
          <span class="token operator">&lt;</span>div<span class="token operator">></span>center<span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span>
        <span class="token operator">&lt;</span><span class="token operator">/</span>Content<span class="token operator">></span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
<span class="token keyword">export</span> <span class="token keyword">default</span> About<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们发现<code v-pre>Content</code>这个组件的<code v-pre>props</code>可以是对象，可以是<code v-pre>jsx</code>，也可以是函数，当子组件用父组件的<code v-pre>props</code>时，我们就当它变量一样在子组件中使用，因此<code v-pre>react</code>中的<code v-pre>props</code>是相当灵活的。</p>
<p><img src="https://files.mdnice.com/user/24614/fcee2c9e-bbfc-4963-82ca-53e3f8a50be8.png" alt=""></p>
<h3 id="react哲学" tabindex="-1"><a class="header-anchor" href="#react哲学" aria-hidden="true">#</a> react哲学</h3>
<p><a href="https://react.docschina.org/docs/thinking-in-react.html" title="`react哲学`" target="_blank" rel="noopener noreferrer"><code v-pre>react哲学</code><ExternalLinkIcon/></a>官方已经用了一篇文章来阐述，通篇下来，官网已经用了一个实际例子来解释<code v-pre>react</code>的哲学思想，总结下来，其实就是以下几点。</p>
<p>1、如何将复杂的UI模块拆分成更细粒度的组件，我们将一个页面拆分成组件，组件依赖数据更清晰，组件之间的耦合度更低。</p>
<p>2、组件的接口<code v-pre>props</code>与<code v-pre>state</code>,要明确知道当前组件的<code v-pre>state</code>是应该放在顶层父组件中，还是当前自身组件</p>
<p>3、因为<code v-pre>react</code>数据流是单向的，在实现父子组件数据流双向过程中，通常用<code v-pre>回调</code>来传递子组件向父组件传递的数据</p>
<p>官方把<code v-pre>react哲学</code>分成了五步走概念，关于组件的拆分，其实我们心里在写代码之前就应该明白哪些组件适合独立拆分，哪些组件不用拆分，当一个页面过于复杂时，此时我们考虑拆分组件的同时，也需要考虑是否组件过于拆分带来的负担，这个因具体情况而定</p>
<h3 id="总结" tabindex="-1"><a class="header-anchor" href="#总结" aria-hidden="true">#</a> 总结</h3>
<ul>
<li>
<p>理解<code v-pre>react</code>构建UI的两种方式，一种是<code v-pre>class</code>方式，一种<code v-pre>纯函数</code>组件方式</p>
</li>
<li>
<p><code v-pre>react</code>数据通信，父子组件如何通信</p>
</li>
<li>
<p>当多个组件存在互相影响时，此时得考虑<code v-pre>状态提升</code>，每个独立的组件状态数据依赖来源必须从顶层组件中传入，并且当需要更新<code v-pre>props</code>时，考虑回调函数修改</p>
</li>
<li>
<p>在<code v-pre>react</code>中实现<code v-pre>vue</code>插槽的功能，也就是<code v-pre>react</code>的组合，<code v-pre>props.children</code>会默认渲染父组件<code v-pre>插槽</code>功能，通过<code v-pre>props</code>指定<code v-pre>jsx</code>可以可以实现具名插槽功能</p>
</li>
<li>
<p>理解<code v-pre>react哲学</code>思想，让我们更灵活的运用<code v-pre>react</code>构建一个完整，维护性很强的<code v-pre>web</code>应用</p>
</li>
<li>
<p><a href="https://github.com/maicFir/lessonNote/tree/master/react/01-react-demo" title="code example" target="_blank" rel="noopener noreferrer">code example<ExternalLinkIcon/></a></p>
</li>
</ul>
</div></template>
