<template><div><p>别被标题吓到，哈哈，即使现在<code v-pre>vite</code>横空出世，社区光芒四射，两个字很快，但是<code v-pre>webpack</code>依旧宝刀未老，依然扛起前端工程化的大梁，但是今天我为啥说要拥抱<code v-pre>gulp</code>，因为我们经常常吃一道菜，所以要换个口味，这样才营养均衡。</p>
<p><code v-pre>gulp</code>定义是：用<code v-pre>自动化构建工具</code>增强你的<code v-pre>工作流程</code>,是一种基于任务<code v-pre>文件流</code>方式,你可以在前端写一些自动化脚本，或者升级历史传统项目，解放你重复打包，压缩，解压之类的操作。</p>
<p>个人理解<code v-pre>gulp</code>是一种<code v-pre>命令式编程</code>的体验，更注重构建过程，所有的任务需要你自己手动创建，你会对构建流程会非常清楚，这点不像<code v-pre>webpack</code>，<code v-pre>webpack</code>就是一个开箱即用的<code v-pre>声明式</code>方式,<code v-pre>webpack</code>是一个模块化打包工具，内部细节隐藏非常之深，你也不需关注细节，你只需要照着提供的<code v-pre>API</code>以及引入对应的<code v-pre>loader</code>和<code v-pre>plugin</code>使用就行。</p>
<p>言归正传，为了<code v-pre>饮食均衡</code>，今天一起学习下<code v-pre>gulpjs</code></p>
<p>正文开始...</p>
<h3 id="搭建一个简单的前端应用" tabindex="-1"><a class="header-anchor" href="#搭建一个简单的前端应用" aria-hidden="true">#</a> 搭建一个简单的前端应用</h3>
<p>相比较<code v-pre>webpack</code>，其实<code v-pre>gulp</code>的项目结构更偏向传统的应用，只是我们借助<code v-pre>gulp</code>工具解放我们的一些<code v-pre>代码压缩</code>、<code v-pre>es6编译</code>、<code v-pre>打包</code>以及在传统项目中都可以使用<code v-pre>less</code>体验。</p>
<p>在<code v-pre>gulp</code>目录下新建<code v-pre>01-simple-demo</code></p>
<p>根目录下生成默认<code v-pre>package.json</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>npm init <span class="token operator">-</span>y
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>然后在<code v-pre>public</code>目录下新建<code v-pre>images</code>、<code v-pre>css</code>、<code v-pre>js</code>、<code v-pre>index.html</code></p>
<p>文件结构，大概就这样
<img src="https://files.mdnice.com/user/24614/9bd5fcfa-6030-4709-a33a-08c09400dd1d.png" alt=""></p>
<p>然后在安装<code v-pre>gulp</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>npm i gulp <span class="token operator">--</span>save<span class="token operator">-</span>dev
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>在根目录下新建<code v-pre>gulpfile.js</code>
我们先在<code v-pre>gulpfile.js</code>中写入一点内容，测试一下</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token function-variable function">defaultTask</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">cb</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'hello gulp'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token function">cb</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
exports<span class="token punctuation">.</span>default <span class="token operator">=</span> defaultTask<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后我们在命令行执行</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>npx gulp
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><img src="https://files.mdnice.com/user/24614/6a5b09c0-2a44-4f77-8868-83c34281061a.png" alt=""></p>
<p>当我们执行<code v-pre>npx gulp</code>时会默认运行<code v-pre>gulpfile.js</code>导出的<code v-pre>default</code>,在<code v-pre>gulpfile.js</code>导出的任务会注册到<code v-pre>gulp</code>任务中</p>
<p>在<code v-pre>gulp</code>中任务主要分两种，一种是<code v-pre>公开任务</code>、另一种是<code v-pre>私有任务</code></p>
<p><code v-pre>公开任务</code>可以直接在命令执行<code v-pre>npx gulp xxx</code>调用执行，比如下面的<code v-pre>defaultTask</code>就是一个公开任务，只要被导出就是一个公开任务,没有被导出就是一个私有任务。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token operator">...</span>
exports<span class="token punctuation">.</span>default <span class="token operator">=</span> defaultTask<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>公有任务<code v-pre>taskJS</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// gulpfile.js</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span> src<span class="token punctuation">,</span> dest <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">pathDir</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">dir</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> path<span class="token punctuation">.</span><span class="token function">resolve</span><span class="token punctuation">(</span>__dirname<span class="token punctuation">,</span> dir<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token comment">// todo 执行ts任务，将js目录下的js打包到dist/js目录下</span>
<span class="token keyword">const</span> <span class="token function-variable function">taskJS</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'public/**/*.js'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">sourcemaps</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">dest</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'dist/js'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
exports<span class="token punctuation">.</span>taskJS <span class="token operator">=</span> taskJS<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后你在命令行执行</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>npx gulp taskJS
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><img src="https://files.mdnice.com/user/24614/3efda27e-ffa8-4a1e-a2dd-8f8385000df6.png" alt="">
<img src="https://files.mdnice.com/user/24614/83520e02-0a89-4ec4-86e3-2ba04bf4fc4f.png" alt="">
至此你会发现<code v-pre>dist</code>目录下就有生成的<code v-pre>js</code>了</p>
<h3 id="安装-less" tabindex="-1"><a class="header-anchor" href="#安装-less" aria-hidden="true">#</a> 安装 less</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>npm i less gulp<span class="token operator">-</span>less <span class="token operator">--</span>save<span class="token operator">-</span>dev
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>在<code v-pre>css/index.less</code>中写入测试 css 的代码</p>
<div class="language-css ext-css line-numbers-mode"><pre v-pre class="language-css"><code><span class="token atrule"><span class="token rule">@bgcolor</span><span class="token punctuation">:</span> yellow<span class="token punctuation">;</span></span>
<span class="token atrule"><span class="token rule">@defaultsize</span><span class="token punctuation">:</span> 20px<span class="token punctuation">;</span></span>
<span class="token selector">body</span> <span class="token punctuation">{</span>
  <span class="token property">background-color</span><span class="token punctuation">:</span> <span class="token atrule"><span class="token rule">@bgcolor</span><span class="token punctuation">;</span></span>
<span class="token punctuation">}</span>
<span class="token selector">h1</span> <span class="token punctuation">{</span>
  <span class="token property">font-size</span><span class="token punctuation">:</span> <span class="token atrule"><span class="token rule">@defaultsize</span><span class="token punctuation">;</span></span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在<code v-pre>gulpfile.js</code>中写入编译<code v-pre>less</code>的任务，需要<code v-pre>gulp-less</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token punctuation">{</span> src<span class="token punctuation">,</span> dest <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> less <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-less'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">pathDir</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">dir</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> path<span class="token punctuation">.</span><span class="token function">resolve</span><span class="token punctuation">(</span>__dirname<span class="token punctuation">,</span> dir<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token operator">...</span>
<span class="token comment">// todo less任务</span>
<span class="token keyword">const</span> <span class="token function-variable function">taskLess</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token comment">// css目录洗的所有.less文件，dest输出到dist/css目录下</span>
  <span class="token keyword">return</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'public/css/*.less'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">less</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">dest</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'dist/css'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
exports<span class="token punctuation">.</span>taskLess <span class="token operator">=</span> taskLess<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>命令行运行<code v-pre>npx gulp taskLess</code>，结果如下
<img src="https://files.mdnice.com/user/24614/8d511316-2996-4f2b-807a-bbf664f7433e.png" alt=""></p>
<h3 id="图片资源" tabindex="-1"><a class="header-anchor" href="#图片资源" aria-hidden="true">#</a> 图片资源</h3>
<p>使用一个<code v-pre>gulp-image</code>插件对图片进行无损压缩处理</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// gulpfile.js</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span> src<span class="token punctuation">,</span> dest <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> image <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-image'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> path <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'path'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">pathDir</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">dir</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> path<span class="token punctuation">.</span><span class="token function">resolve</span><span class="token punctuation">(</span>__dirname<span class="token punctuation">,</span> dir<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token operator">...</span>
<span class="token comment">// todo 图片资源</span>
<span class="token keyword">const</span> <span class="token function-variable function">taskImage</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'public/images/*.*'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">image</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">dest</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'dist/images'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
exports<span class="token punctuation">.</span>taskImage <span class="token operator">=</span> taskImage<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="https://files.mdnice.com/user/24614/0386247b-f3d8-4f80-96bb-8ec5cfc20e1d.png" alt=""></p>
<p>一顿操作发现，最新版本不支持<code v-pre>esm</code>,所以还是降低版本版本，这里降低到<code v-pre>6.2.1</code>版本</p>
<p>然后运行<code v-pre>npx gulp taskImage</code>
<img src="https://files.mdnice.com/user/24614/f8931764-69ae-41f5-9d26-d91656957f12.png" alt="">
图片压缩得不小</p>
<p>在这之前，我们分别定义了三个不同的任务，<code v-pre>gulp</code>导出的任务有
公开任务和私有任务，多个公开任务可以<code v-pre>串行组合</code>使用</p>
<h3 id="组合任务-series-与-parallel" tabindex="-1"><a class="header-anchor" href="#组合任务-series-与-parallel" aria-hidden="true">#</a> 组合任务 series 与 parallel</h3>
<p>因此我可以将之前的介个任务组合在一起</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// gulpfile.js</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span> src<span class="token punctuation">,</span> dest<span class="token punctuation">,</span> series <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> less <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-less'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> image <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-image'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> path <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'path'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">pathDir</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">dir</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> path<span class="token punctuation">.</span><span class="token function">resolve</span><span class="token punctuation">(</span>__dirname<span class="token punctuation">,</span> dir<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token comment">// todo js任务</span>
<span class="token keyword">const</span> <span class="token function-variable function">taskJS</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'public/**/*.js'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">sourcemaps</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">dest</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'dist/js'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
<span class="token operator">...</span>
<span class="token comment">// series组合多个任务</span>
<span class="token keyword">const</span> seriseTask <span class="token operator">=</span> <span class="token function">series</span><span class="token punctuation">(</span>taskJS<span class="token punctuation">,</span> taskLess<span class="token punctuation">,</span> taskLess<span class="token punctuation">,</span> taskImage<span class="token punctuation">)</span>
exports<span class="token punctuation">.</span>seriseTask <span class="token operator">=</span> seriseTask<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当我在命令行<code v-pre>npx gulp seriseTask</code>时
<img src="https://files.mdnice.com/user/24614/646e2620-66d2-48af-865e-9989a568bbeb.png" alt="">
已经在<code v-pre>dist</code>生成对应的文件了</p>
<h3 id="编译转换-es6" tabindex="-1"><a class="header-anchor" href="#编译转换-es6" aria-hidden="true">#</a> 编译转换 es6</h3>
<p>在我们<code v-pre>index.js</code>，很多时候是写的<code v-pre>es6</code>，在<code v-pre>gulp</code>中我们需要一些借助一些插件<code v-pre>gulp-babel</code>,另外我们需要安装另外两个<code v-pre>babel</code>核心插件<code v-pre>@babel/core</code>,<code v-pre>@babel/preset-env</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code> npm i gulp<span class="token operator">-</span>babel @babel<span class="token operator">/</span>core @babel<span class="token operator">/</span>preset<span class="token operator">-</span>env
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>在<code v-pre>gulpfile.js</code>中我们需要修改下</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token operator">...</span>
<span class="token keyword">const</span> babel <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-babel'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// todo js任务</span>
<span class="token comment">// 用babel转换es6语法糖</span>
<span class="token keyword">const</span> <span class="token function-variable function">taskJS</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'public/**/*.js'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">sourcemaps</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">babel</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token literal-property property">presets</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">'@babel/preset-env'</span><span class="token punctuation">]</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">dest</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'dist/js'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当我们在<code v-pre>js/index.js</code>写入一段测试代码</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>js <span class="token operator">/</span> index<span class="token punctuation">.</span>js<span class="token punctuation">;</span>
<span class="token keyword">const</span> appDom <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">getElementById</span><span class="token punctuation">(</span><span class="token string">'app'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
appDom<span class="token punctuation">.</span>innerHTML <span class="token operator">=</span> <span class="token string">'hello gulp'</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">fn</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'公众号：Web技术学苑，好好学习，天天向上'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token function">fn</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>运行<code v-pre>npx gulp seriseTask</code>
<img src="https://files.mdnice.com/user/24614/6c69c15e-5e5b-45ff-99cf-dd91df5652de.png" alt="">
箭头函数和<code v-pre>const</code>申明的变量就变成了<code v-pre>es5</code>了</p>
<p>通常情况下，一般打包后的<code v-pre>dist</code>下的<code v-pre>css</code>或者<code v-pre>js</code>都会被压缩,在<code v-pre>gulp</code>中也是需要借助插件来完成</p>
<h3 id="压缩-js-与-css" tabindex="-1"><a class="header-anchor" href="#压缩-js-与-css" aria-hidden="true">#</a> 压缩 js 与 css</h3>
<p>压缩<code v-pre>js</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token operator">...</span>
<span class="token keyword">const</span> teser <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-terser'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// todo js任务</span>
<span class="token keyword">const</span> <span class="token function-variable function">taskJS</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'public/**/*.js'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">sourcemaps</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">babel</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token literal-property property">presets</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">'@babel/preset-env'</span><span class="token punctuation">]</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">teser</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token literal-property property">mangle</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">toplevel</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token comment">// 混淆代码</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">dest</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'dist/js'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
<span class="token operator">...</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>压缩<code v-pre>css</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token operator">...</span>
<span class="token keyword">const</span> uglifycss <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-uglifycss'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// todo less任务</span>
<span class="token keyword">const</span> <span class="token function-variable function">taskLess</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'public/css/*.less'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">less</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">uglifycss</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">dest</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'dist/css'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
<span class="token operator">...</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在这之前我们在输出<code v-pre>dest</code>时候我们都执向了一个具体的文件目录，在<code v-pre>src</code>这个<code v-pre>api</code>中是创建流，从文件中读取<code v-pre>vunyl</code>对象，本身也提供了一个<code v-pre>base</code>属性，因此你可以像下面这样写</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token punctuation">{</span> src<span class="token punctuation">,</span> dest<span class="token punctuation">,</span> series <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> less <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-less'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> image <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-image'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> babel <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-babel'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> teser <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-terser'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> uglifycss <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-uglifycss'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> path <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'path'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">pathDir</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">dir</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> path<span class="token punctuation">.</span><span class="token function">resolve</span><span class="token punctuation">(</span>__dirname<span class="token punctuation">,</span> dir<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token comment">// 设置base，当输出文件目标dist文件时，会自动拷贝当前文件夹到目标目录</span>
<span class="token keyword">const</span> basePath <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">base</span><span class="token operator">:</span> <span class="token string">'./public'</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token comment">// todo js任务</span>
<span class="token keyword">const</span> <span class="token function-variable function">taskJS</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'public/**/*.js'</span><span class="token punctuation">,</span> basePath<span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span>
      <span class="token function">babel</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
        <span class="token literal-property property">presets</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">'@babel/preset-env'</span><span class="token punctuation">]</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span>
      <span class="token function">teser</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
        <span class="token literal-property property">mangle</span><span class="token operator">:</span> <span class="token punctuation">{</span>
          <span class="token literal-property property">toplevel</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token comment">// 混淆代码</span>
        <span class="token punctuation">}</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">dest</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'dist'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token comment">// todo less任务</span>
<span class="token keyword">const</span> <span class="token function-variable function">taskLess</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'public/css/*.less'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> basePath<span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">less</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">uglifycss</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">dest</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'dist'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token comment">// todo 图片资源，有压缩，并输出到对应的dist/images文件夹下</span>
<span class="token keyword">const</span> <span class="token function-variable function">taskImage</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'public/images/*.*'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> basePath<span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">image</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">dest</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'dist'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token comment">// todo html</span>
<span class="token keyword">const</span> <span class="token function-variable function">taskHtml</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'public/index.html'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> basePath<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">dest</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'dist'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">defaultTask</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">cb</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'hello gulp'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token function">cb</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>

<span class="token comment">// series组合多个任务</span>
<span class="token keyword">const</span> seriseTask <span class="token operator">=</span> <span class="token function">series</span><span class="token punctuation">(</span>taskHtml<span class="token punctuation">,</span> taskJS<span class="token punctuation">,</span> taskLess<span class="token punctuation">,</span> taskLess<span class="token punctuation">,</span> taskImage<span class="token punctuation">)</span><span class="token punctuation">;</span>

exports<span class="token punctuation">.</span>default <span class="token operator">=</span> defaultTask<span class="token punctuation">;</span>
exports<span class="token punctuation">.</span>taskJS <span class="token operator">=</span> taskJS<span class="token punctuation">;</span>
exports<span class="token punctuation">.</span>taskLess <span class="token operator">=</span> taskLess<span class="token punctuation">;</span>
exports<span class="token punctuation">.</span>taskImage <span class="token operator">=</span> taskImage<span class="token punctuation">;</span>
exports<span class="token punctuation">.</span>seriseTask <span class="token operator">=</span> seriseTask<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="将资源注入-html-中" tabindex="-1"><a class="header-anchor" href="#将资源注入-html-中" aria-hidden="true">#</a> 将资源注入 html 中</h3>
<p>在<code v-pre>gulp</code>中，任务之间的依赖关系需要我们自己手动写一些执行任务流，现在一些打包后的<code v-pre>dist</code>的文件并不会自动注入<code v-pre>html</code>中。</p>
<p>参考<a href="https://www.npmjs.com/package/gulp-inject" title="gulp-inject" target="_blank" rel="noopener noreferrer">gulp-inject<ExternalLinkIcon/></a></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token operator">...</span>
<span class="token keyword">const</span> inject <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-inject'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token operator">...</span>
<span class="token comment">// 将css,js插入html中</span>
<span class="token keyword">const</span> <span class="token function-variable function">injectHtml</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token comment">// 目标资源</span>
  <span class="token keyword">const</span> targetSources <span class="token operator">=</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'./dist/**/*.js'</span><span class="token punctuation">,</span> <span class="token string">'./dist/**/*.css'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">read</span><span class="token operator">:</span> <span class="token boolean">false</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// 目标html</span>
  <span class="token keyword">const</span> targetHtml <span class="token operator">=</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token string">'./dist/*.html'</span><span class="token punctuation">)</span>
  <span class="token comment">// 把目标资源插入目标html中，同时输出到dist文件下</span>
  <span class="token keyword">const</span> result <span class="token operator">=</span> targetHtml<span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">inject</span><span class="token punctuation">(</span>targetSources<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">dest</span><span class="token punctuation">(</span><span class="token string">'dist'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">return</span> result
<span class="token punctuation">}</span>
<span class="token comment">// series串行组合多个任务</span>
<span class="token keyword">const</span> seriseTask <span class="token operator">=</span> <span class="token function">series</span><span class="token punctuation">(</span>taskHtml<span class="token punctuation">,</span> taskJS<span class="token punctuation">,</span> taskLess<span class="token punctuation">,</span> taskLess<span class="token punctuation">,</span> taskImage<span class="token punctuation">,</span> injectHtml<span class="token punctuation">)</span>

exports<span class="token punctuation">.</span>seriseTask <span class="token operator">=</span> seriseTask<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>注意一个执行顺序，必须是等前面任务执行完了，再注入，所以在<code v-pre>series</code>任务的最后才执行<code v-pre>injectHtml</code>操作</p>
<p>并且在<code v-pre>public/index.html</code>下，还需要加入一段注释</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token doctype"><span class="token punctuation">&lt;!</span><span class="token doctype-tag">DOCTYPE</span> <span class="token name">html</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>html</span> <span class="token attr-name">lang</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>en<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>head</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">charset</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>UTF-8<span class="token punctuation">"</span></span> <span class="token punctuation">/></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">http-equiv</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>X-UA-Compatible<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>IE=edge<span class="token punctuation">"</span></span> <span class="token punctuation">/></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>viewport<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>width=device-width, initial-scale=1.0<span class="token punctuation">"</span></span> <span class="token punctuation">/></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>title</span><span class="token punctuation">></span></span>gulp<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>title</span><span class="token punctuation">></span></span>
    <span class="token comment">&lt;!-- inject:css --></span>
    <span class="token comment">&lt;!-- endinject --></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>head</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>body</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>app<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
    <span class="token comment">&lt;!-- inject:js --></span>
    <span class="token comment">&lt;!-- endinject --></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>html</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当我们运行<code v-pre>npx gulp seriseTask</code>时
<img src="https://files.mdnice.com/user/24614/3068ad7b-eeeb-4323-9128-74a3cd4edb11.png" alt=""></p>
<h3 id="创建本地服务" tabindex="-1"><a class="header-anchor" href="#创建本地服务" aria-hidden="true">#</a> 创建本地服务</h3>
<p>参考<a href="https://browsersync.io/docs/gulp" title="browser-sync" target="_blank" rel="noopener noreferrer">browser-sync<ExternalLinkIcon/></a></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token punctuation">{</span> src<span class="token punctuation">,</span> dest<span class="token punctuation">,</span> series<span class="token punctuation">,</span> watch <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> browserSync <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'browser-sync'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token operator">...</span>

<span class="token keyword">const</span> taskBuild <span class="token operator">=</span> seriseTask<span class="token punctuation">;</span>
<span class="token comment">// 本地服务</span>
<span class="token keyword">const</span> <span class="token function-variable function">taskDevServer</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token comment">// 监听public所有目录下，只要文件发生改变，就重新加载</span>
  <span class="token function">watch</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'public'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> taskBuild<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// 创建服务</span>
  <span class="token keyword">const</span> server <span class="token operator">=</span> browserSync<span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// 调用init开启端口访问</span>
  server<span class="token punctuation">.</span><span class="token function">init</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token literal-property property">port</span><span class="token operator">:</span> <span class="token string">'8081'</span><span class="token punctuation">,</span> <span class="token comment">//设置端口</span>
    <span class="token literal-property property">open</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>  <span class="token comment">// 自动打开浏览器</span>
    <span class="token literal-property property">files</span><span class="token operator">:</span> <span class="token string">'./dist/*'</span><span class="token punctuation">,</span> <span class="token comment">// dist文件</span>
    <span class="token literal-property property">server</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">baseDir</span><span class="token operator">:</span> <span class="token string">'./dist'</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
exports<span class="token punctuation">.</span>taskDevServer <span class="token operator">=</span> taskDevServer<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当我们运行<code v-pre>npx gulp taskDevServer</code>时，浏览器会默认打开<code v-pre>http://localhost:8081</code></p>
<p><img src="https://files.mdnice.com/user/24614/12d77b8b-379b-4922-9d72-05029484cbe3.png" alt=""></p>
<p>我们使用了一个<code v-pre>watch</code>监听<code v-pre>public</code>目录下的所有文件，如果文件有变化时，会执行<code v-pre>taskBuild</code>任务会在<code v-pre>dist</code>目录下生成对应的文件，然后会启动一个本地服务，打开一个<code v-pre>8081</code>的端口就可以访问应用了。</p>
<p>至此一个一个用<code v-pre>gulp</code>搭建的前端应用终于可以了。</p>
<h3 id="重新组织-gulpfile" tabindex="-1"><a class="header-anchor" href="#重新组织-gulpfile" aria-hidden="true">#</a> 重新组织 gulpfile</h3>
<p>最后我们可以再重新组织一下<code v-pre>gulpfile.js</code>，因为多个任务写在一个文件里貌似不太那么好维护，随着业务迭代，会越来越多，因此，有必要将任务分解一下</p>
<p>在根目录新建<code v-pre>task</code>，我们把所有的任务如下</p>
<p><code v-pre>common.js</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// task/common.js</span>
<span class="token keyword">const</span> path <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'path'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">pathDir</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">dir</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> path<span class="token punctuation">.</span><span class="token function">join</span><span class="token punctuation">(</span>__dirname<span class="token punctuation">,</span> <span class="token string">'../'</span><span class="token punctuation">,</span> dir<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> rootDir <span class="token operator">=</span> path<span class="token punctuation">.</span><span class="token function">resolve</span><span class="token punctuation">(</span>__dirname<span class="token punctuation">,</span> <span class="token string">'../'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> basePath <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">base</span><span class="token operator">:</span> <span class="token string">'./public'</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> targetDest <span class="token operator">=</span> <span class="token string">'dist'</span><span class="token punctuation">;</span>
module<span class="token punctuation">.</span>exports <span class="token operator">=</span> <span class="token punctuation">{</span>
  rootDir<span class="token punctuation">,</span>
  pathDir<span class="token punctuation">,</span>
  basePath<span class="token punctuation">,</span>
  targetDest
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>injectHtml.js</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// task/injectHtml.js</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span> src<span class="token punctuation">,</span> dest <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> inject <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp-inject'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span> targetDest<span class="token punctuation">,</span> rootDir <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'./common.js'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 将css,js插入html中</span>
<span class="token keyword">const</span> <span class="token function-variable function">injectHtml</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token comment">// 目标资源</span>
  <span class="token keyword">const</span> targetSources <span class="token operator">=</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>rootDir<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>targetDest<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/**/*.js</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>rootDir<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>targetDest<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/**/*.css</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// 目标html</span>
  <span class="token keyword">const</span> targetHtml <span class="token operator">=</span> <span class="token function">src</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>rootDir<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>targetDest<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/*.html</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// 把目标资源插入目标html中，同时输出到dist文件下</span>
  <span class="token keyword">const</span> result <span class="token operator">=</span> targetHtml<span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">inject</span><span class="token punctuation">(</span>targetSources<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">relative</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span><span class="token function">dest</span><span class="token punctuation">(</span>targetDest<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">return</span> result<span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
module<span class="token punctuation">.</span>exports <span class="token operator">=</span> injectHtml<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>taskDevServer.js</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token punctuation">{</span> watch <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> path <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'path'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> browserSync <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'browser-sync'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span> pathDir<span class="token punctuation">,</span> targetDest<span class="token punctuation">,</span> rootDir <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'./common.js'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">taskDevServer</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">taskBuild</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token parameter">options <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> defaultOption <span class="token operator">=</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">port</span><span class="token operator">:</span> <span class="token string">'8081'</span><span class="token punctuation">,</span> <span class="token comment">//设置端口</span>
      <span class="token literal-property property">open</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token comment">// 自动打开浏览器</span>
      <span class="token literal-property property">files</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>rootDir<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>targetDest<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/*</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token comment">// 当dist文件下有改动时，会自动刷新页面</span>
      <span class="token literal-property property">server</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">baseDir</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>rootDir<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>targetDest<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span> <span class="token comment">// 基于当前dist目录</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
      <span class="token operator">...</span>options
    <span class="token punctuation">}</span><span class="token punctuation">;</span>
    <span class="token comment">// 监听public所有目录下，只要文件发生改变，就重新加载</span>
    <span class="token function">watch</span><span class="token punctuation">(</span><span class="token function">pathDir</span><span class="token punctuation">(</span><span class="token string">'public'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> taskBuild<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> server <span class="token operator">=</span> browserSync<span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    server<span class="token punctuation">.</span><span class="token function">init</span><span class="token punctuation">(</span>defaultOption<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
module<span class="token punctuation">.</span>exports <span class="token operator">=</span> taskDevServer<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>...</p>
<p><code v-pre>task/index.js</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> injectHtml <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'./injectHtml.js'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> taskDevServer <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'./taskDevServer.js'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> taskHtml <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'./taskHtml.js'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> taskImage <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'./taskImage.js'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> taskJS <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'./taskJS.js'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> taskLess <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'./taskLess.js'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
module<span class="token punctuation">.</span>exports <span class="token operator">=</span> <span class="token punctuation">{</span>
  injectHtml<span class="token punctuation">,</span>
  taskDevServer<span class="token punctuation">,</span>
  taskHtml<span class="token punctuation">,</span>
  taskImage<span class="token punctuation">,</span>
  taskJS<span class="token punctuation">,</span>
  taskLess
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在<code v-pre>gulpfile.js</code>中，我们修改下</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">// gulpfile.js</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span> series <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'gulp'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token punctuation">{</span> injectHtml<span class="token punctuation">,</span> taskDevServer<span class="token punctuation">,</span> taskHtml<span class="token punctuation">,</span> taskImage<span class="token punctuation">,</span> taskJS<span class="token punctuation">,</span> taskLess <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'./task/index.js'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// series组合多个任务</span>
<span class="token keyword">const</span> seriseTask <span class="token operator">=</span> <span class="token function">series</span><span class="token punctuation">(</span>taskHtml<span class="token punctuation">,</span> taskJS<span class="token punctuation">,</span> taskLess<span class="token punctuation">,</span> taskLess<span class="token punctuation">,</span> taskImage<span class="token punctuation">,</span> injectHtml<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 本地服务</span>
<span class="token keyword">const</span> devServer <span class="token operator">=</span> <span class="token function">taskDevServer</span><span class="token punctuation">(</span>seriseTask<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 启动服务</span>
<span class="token keyword">const</span> <span class="token function-variable function">server</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token function">devServer</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token literal-property property">port</span><span class="token operator">:</span> <span class="token number">9000</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> taskBuild <span class="token operator">=</span> seriseTask<span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token function-variable function">defaultTask</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">cb</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'hello gulp'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token function">cb</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
exports<span class="token punctuation">.</span>default <span class="token operator">=</span> defaultTask<span class="token punctuation">;</span>
exports<span class="token punctuation">.</span>server <span class="token operator">=</span> server<span class="token punctuation">;</span>
exports<span class="token punctuation">.</span>build <span class="token operator">=</span> taskBuild<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们在<code v-pre>package.json</code>中新增命令</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code>  <span class="token property">"scripts"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token property">"test"</span><span class="token operator">:</span> <span class="token string">"echo \"Error: no test specified\" &amp;&amp; exit 1"</span><span class="token punctuation">,</span>
    <span class="token property">"server"</span><span class="token operator">:</span> <span class="token string">"gulp server"</span><span class="token punctuation">,</span>
    <span class="token property">"build"</span><span class="token operator">:</span> <span class="token string">"gulp build"</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>npm run build</code>
<img src="https://files.mdnice.com/user/24614/6a153691-c44a-4c10-babd-3db13e18e3e1.png" alt=""></p>
<p>在启动<code v-pre>server</code>之前，我们先执行<code v-pre>npm run build</code>，然后再执行下面命令,保证<code v-pre>browserSync</code>创建的服务文件夹存在，不然页面打开就<code v-pre>404</code>错误</p>
<p><code v-pre>npm run server</code>
<img src="https://files.mdnice.com/user/24614/6ad27744-68ad-44c6-b5fb-aac0fd3cc5f0.png" alt=""></p>
<p>至此<code v-pre>gulp</code>搭建一个简单的应该就已经完全 ok 了
<img src="https://files.mdnice.com/user/24614/1ecf7254-507b-4956-9282-07de62271e7a.png" alt=""></p>
<p>页面背景貌似有点黄
<img src="https://img.soogif.com/2Y2r9Qj6ydfIQFGKMWJNE2lUUGwzfymA.gif?scope=mdnice" alt=""></p>
<h3 id="总结" tabindex="-1"><a class="header-anchor" href="#总结" aria-hidden="true">#</a> 总结</h3>
<ul>
<li>
<p><code v-pre>gulpjs</code>开发是一个任务流的开发方式，它的核心思想就是<code v-pre>用自动化构建工具增强你的工作流</code>,所有的自动化工作流操作都牢牢的掌握在自己手上，你可以用<code v-pre>gulp</code>写一些自动化脚本，比如，文件上传，打包，压缩，或者改造传统的前端应用。</p>
</li>
<li>
<p>用<code v-pre>gulp</code>写了一个简单的应用，但是发现中途需要找好多<code v-pre>gulp</code>插件，<code v-pre>gulp</code>的生态还算可以，<code v-pre>3w</code>多个 star，生态相对丰富，但是有些插件常年不更新，或者版本更新不支持，比如<code v-pre>gulp-image</code>，当你按照官方文档使用最新的包时，不支持 esm，你必须降低版本<code v-pre>6.2.1</code>,改用<code v-pre>cjs</code>才行</p>
</li>
<li>
<p>使用<code v-pre>gulp</code>的一些常用的 api,比如<code v-pre>src</code>、<code v-pre>dest</code>、<code v-pre>series</code>,以及<code v-pre>browser-sync</code>实现本地服务，更多<a href="https://www.gulpjs.com.cn/docs/api/src/" title="api" target="_blank" rel="noopener noreferrer">api<ExternalLinkIcon/></a>参考官方文档。</p>
</li>
<li>
<p>即使项目时间再多，也不要用<code v-pre>gulp</code>搭建前端应用，因为<code v-pre>webpack</code>生态很强大了，看<code v-pre>gulp</code>的最近更新还是 2 年前，但是写个自动化脚本，还算可以，毕竟<code v-pre>gulp</code>的理念就是<code v-pre>用自动化构建工具增强你工作流程</code>，也许当你接盘传统项目时，一些打包，拷贝，压缩文件之类的，可以尝试用用这个。</p>
</li>
<li>
<p>本文示例<a href="https://github.com/maicFir/lessonNote/tree/master/gulp/01-simple-demo" title="code-example" target="_blank" rel="noopener noreferrer">code-example<ExternalLinkIcon/></a></p>
</li>
</ul>
</div></template>
